### ISSUE TITLE
Github query returns empty list

### ISSUE THREAD

**Issue by SimoMay** [bjesus/teatime#7]
Github query returns empty list right now.

`GET https://api.github.com/search/repositories?q=topic:teatime-database&sort=stars&order=desc`

Response:
```json
{
  "total_count": 0,
  "incomplete_results": false,
  "items": []
}
```

**Comment by bjesus** [comment]
Just noticed it too, wondering if it's just a glitch with the API or did GitHub decide to block it for some reason. Checking...

**Comment by bjesus** [comment]
Seem to have resolved itself 🙏
